#!/usr/bin/env bash
set -e

BASE_DIR="/home/ec2-user/app"
APP_DIR="/home/ec2-user/app/app"
OBS_DIR="/home/ec2-user/app/obs"

while read oldrev newrev ref
do
  branch=$(git rev-parse --symbolic --abbrev-ref $ref)
  if [ "$branch" = "main" ]; then
    # Pull the latest code and build the Docker image
    git --work-tree=$BASE_DIR checkout -f main

    # Run the obs container
    cd "$OBS_DIR"
    echo "Running the Docker container for the obs service..."
    docker network create obs-net 2>/dev/null || true
    docker-compose down
    docker-compose up -d
    docker ps
  fi
done
